apiVersion: v1
data:
  aes256-sharesecret-1.txt: NkQ1QUJGMzY3NDYyMzY5MkZBOTcwRTJBMjlGNjgwMkZENDkzMEZFMzU5NzU2RTBFNEVBM0NBMjA4MzYwNDUxMwo=
kind: Secret
metadata:
  creationTimestamp: null
  name: booking-service-secret3
  namespace: dp01-dev
