apiVersion: v1
data:
  aes256-sharesecret-1.txt: MDU0MUE4QTI2OUMxMTQ5RkRENjJGMjAyRUQ5OUUyMjQ4RTdBQTAyRUUyMzNCMTNCRUREM0QzRjNDNUNDOTZDNwo=
kind: Secret
metadata:
  creationTimestamp: null
  name: booking-service-secret3
  namespace: dp01-dev
